(define (script-correct-distortion filename distortion-main distortion-edge)
	(let* ((image-file (car (gimp-file-load RUN-NONINTERACTIVE filename filename)))
		(image-layer (car (gimp-image-get-active-layer image-file))))
		(plug-in-lens-distortion RUN-NONINTERACTIVE image-file image-layer 0 0 distortion-main distortion-edge 0 0)
		(gimp-file-save RUN-NONINTERACTIVE image-file image-layer filename filename)
		(gimp-image-delete image-file)))

(define (script-correct-distortion-multiple file-pattern distortion-main distortion-edge)
	(let* ((file-list (cadr (file-glob file-pattern 1))))
		(while (not (null? file-list))
			(let* ((file-name (car file-list))
			(image-file (car (gimp-file-load RUN-NONINTERACTIVE file-name file-name)))
			(image-layer (car (gimp-image-get-active-layer image-file))))
			(plug-in-lens-distortion RUN-NONINTERACTIVE image-file image-layer 0 0 distortion-main distortion-edge 0 0)
			(gimp-file-save RUN-NONINTERACTIVE image-file image-layer file-name file-name)
			(gimp-image-delete image-file))
			(set! file-list (cdr file-list)))))
